// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmHZT9IERP6Fc9tcUhCVHGuf-O2uayozY',
    appId: '1:89719610062:web:b72ade1a23ec8a0e340e9f',
    messagingSenderId: '89719610062',
    projectId: 'mghgroup-ca7c2',
    authDomain: 'mghgroup-ca7c2.firebaseapp.com',
    storageBucket: 'mghgroup-ca7c2.firebasestorage.app',
    measurementId: 'G-YJ0JKLK6SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgbVDMp0ZDdPzWvnYHibWXwyOMU5Gt2sA',
    appId: '1:89719610062:android:d330ebf5c7d74916340e9f',
    messagingSenderId: '89719610062',
    projectId: 'mghgroup-ca7c2',
    storageBucket: 'mghgroup-ca7c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFK35srXqRm8Cn8AZBKIaboWa4UVJCXHc',
    appId: '1:89719610062:ios:9498e1725f923811340e9f',
    messagingSenderId: '89719610062',
    projectId: 'mghgroup-ca7c2',
    storageBucket: 'mghgroup-ca7c2.firebasestorage.app',
    iosBundleId: 'com.example.mgh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFK35srXqRm8Cn8AZBKIaboWa4UVJCXHc',
    appId: '1:89719610062:ios:9498e1725f923811340e9f',
    messagingSenderId: '89719610062',
    projectId: 'mghgroup-ca7c2',
    storageBucket: 'mghgroup-ca7c2.firebasestorage.app',
    iosBundleId: 'com.example.mgh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmHZT9IERP6Fc9tcUhCVHGuf-O2uayozY',
    appId: '1:89719610062:web:a792b2797d4b690b340e9f',
    messagingSenderId: '89719610062',
    projectId: 'mghgroup-ca7c2',
    authDomain: 'mghgroup-ca7c2.firebaseapp.com',
    storageBucket: 'mghgroup-ca7c2.firebasestorage.app',
    measurementId: 'G-66QVWDXJV5',
  );
}
